import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import AuthProviders from "./_providers/auth";
import { Toaster } from "sonner";

const mulish = Mulish({
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.className} antialiased dark`}>
        <AuthProviders>
          {children}
          <Toaster />
        </AuthProviders>
      </body>
    </html>
  );
}
